class DriveMap:
    PWM_LEFT_FRONT = 0
    PWM_LEFT_BACK = 1
    PWM_RIGHT_FRONT = 2
    PWM_RIGHT_BACK = 3

    DIO_ENCODER_RIGHT_A = 0
    DIO_ENCODER_RIGHT_B = 1
    DIO_ENCODER_LEFT_A = 2
    DIO_ENCODER_LEFT_B = 3

class JoystickMap:
    PORT_LEFT = 0
    PORT_RIGHT = 1
    PORT_CONTROLLER = 2
